# Generated by Django 3.2.8 on 2021-11-02 09:19

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Depot Name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Depot Address')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Depot Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Courier Name')),
                ('capacity', models.PositiveIntegerField(verbose_name='Courier Capacity')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Client Address')),
                ('demand', models.PositiveIntegerField(verbose_name='Client Demand')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Client Location')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
